version: "3.1"

services:
  web:
    image: odoo:19
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./custom_addons:/mnt/custom-addons # Carpeta para los módulos personalizados
      - ./odoo.conf:/etc/odoo/odoo.conf # Archivo de configuración de Odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - MASTER_PASSWORD=admin 

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./postgresql:/var/lib/postgresql/data # Guarda los datos de la base de datos

volumes:
  pg_data:
